import stl from './browse.module.scss'

import Head from "next/head";

import FrontLayout from "../../components/layout/frontLayout";
import { ReactElement } from "react";
import BrowseSide from '../../components/browseSide/browseSide';

const Browse = () => {
  return (
    <>
      <Head>
        <title>WebnovelClone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={stl.container}>
        <h1>Browse Page</h1>
        <BrowseSide />
      </div>
    </>
  );
};

Browse.getLayout = function getLayout(page: ReactElement) {
  return <FrontLayout>{page}</FrontLayout>;
};

export default Browse;
